### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Uchiha-SR** [cnrture/E-Commerce-App#2]
Hi. i  am trying to build this app from scratch. i would like to know how do you add all the details to the firestore especially the images.

**Comment by cnrture** [comment]
Hi, in this repo you can find examples of how to add data and images to firestore. It's really simple 😀

https://github.com/cnrture/Firebase-Samples
StorageOperationsWrapper.kt and FirestoreOperationsWrapper.kt ✌️😀
